### ISSUE TITLE
Default values during pull

### ISSUE THREAD

**Issue by chrisdanek** [mdyd-dev/marketplace-kit#20]
Populating properties that have unchanged default values results in unnecessary bloat, for example

Before pull
```yml
- name: discipline
  attribute_type: string
  label: Discipline
```

After pull:

```yml
- name: discipline
  attribute_type: string
  html_tag: input
  input_html_options: {}
  label: Discipline
  public: true
  search_in_query: false
  searchable: false
```
